### ISSUE TITLE
Rewrite README with a clear overview of what the cookiecutter does and how to get started.

### ISSUE THREAD

**Issue by rochecompaan** [sixfeetup/scaf#129]
Rewrite the README to include:
1. A high-level overview of the project
2. Architecture of a target project
3. Concise usage instructions and what options are available

Remove the list of Python packages.

**Comment by hillairet** [comment]
I wouldn't mind taking that one on.

I would use section titles as questions such as "What is the architecture?" and HowTo such as "How to set up your local environment for development".
I find that these help create focus and clarify the purpose of the section for both the writer and the reader.

Example in Beck's [README](https://github.com/sixfeetup/becks-soil/blob/main/README.md)

**Comment by hillairet** [comment]
Oh also, what about the use of emojis for section titles? 
I find them quite helpful when scrolling through a large single-page README.

**Comment by rochecompaan** [comment]
Since I logged this ticket, I have already made a few updates to the README:
* https://github.com/sixfeetup/scaf/pull/158/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
* https://github.com/sixfeetup/scaf/pull/158/files#diff-a3114d707f7bb6efd153cfbe0266a64148252b8f82a443312b214c34a4b99f42

Note that the README for Scaf differs from the README for the generated project.

There is a PR of an architecture diagram, but it is outdated now:
https://github.com/sixfeetup/scaf/pull/126/files

I think we can close this issue and re-open more specific issues for updates to the README since the Scaf README provides a workable general overview, and the instructions for the generated project are mostly accurate.
