### ISSUE TITLE
Add Next.js to Scaf

### ISSUE THREAD

**Issue by sedatbasar** [sixfeetup/scaf#187]
**Background:**
Currently when user wants to have a frontend app as well, there is only 1 single option which is a React + Typescript app.
We need to support more options

**AC:**
* Add option to select NextJS framework for frontend

- [x] #198
- [x] #199
- [x] #201
- [x] #203
- [x] #260
- [x] #261

**Comment by abosio** [comment]
What we need to do is change the create_react_frontend from y/n to "Create a frontend?" with options of Next.js and Remix.

The React team has announced that new projects should not use React directly, so we want to remove that from Scaf.
