### ISSUE TITLE
Allow underscores in project slug

### ISSUE THREAD

**Issue by clshaw01** [sixfeetup/scaf#322]
Project slug is a required argument and uses an underscore in the suggestion. Currently, underscores are not allowed in the project slug.

Allow underscores for usage in the project slug.

**Comment by gfranxman** [comment]
The project slug needs to be a valid python identifier, as required by python's str.isidentifier method, and it needs to be a valid cluster name for kind.

Python only allows underscores.  ( the slug is used for package naming )
Kind only allows hyphens. ( the slug is used for hostnames )

We could ask for the slug, allowing both, but then derive a python_slug and a kind_slug.  I haven't yet found where they would need to match exactly.

**Comment by gfranxman** [comment]
that's what I ended up doing, using a COOKIECUTTER_SLUG and CLUSTER_SLUG each of which are translations of the given PROJECT_SLUG.
