### ISSUE TITLE
Create branch for testing : switch from piptools to uv

### ISSUE THREAD

**Issue by clshaw01** [sixfeetup/scaf#346]
- Create a feature branch to test switching from using `piptools` to `uv`.  
- Test speed/performance gains between the two.
- Identify any "gotchas" for the team regarding the switch.

**Origin story:**
Calvin spoke with Michael Kennedy and he loved the experience, he had one optimization that I think we should try to do, replace our usage of piptools with uv. He said it will be a non-trivial speedup and if we are showcasing fast, this is the way.

**Glenn's concerns:**
> I'm not clear on the whole process for generating pins with it though.    I basically just uv venv then cd . to activate it through my cd hook, then uv pip install somepackage==3.2.1`  uv pip install -r requirements.txt Basically I saw it as a replacement for python -m venv .venv with a wrapper for pip.  Does it speed up pip-tools for compiling our .in's ?   Also, maybe we can use the .envrc to alias pip to uv pip.

**Comment by calvinhp** [comment]
This includes an example of a major speedup of the `pip-tools compile` and I switch most every other usage of `pip install` with `uv pip install` and all is faster.
