### ISSUE TITLE
Add docs directory for beginning of developer's guide

### ISSUE THREAD

**Issue by clshaw01** [sixfeetup/scaf#365]
In the project's output, include subdirectories for developer's handbook, etc.

Initial structure should be (suggested):
- /docs/development (ask Christine for sample docs)
  - /getting-started
  - ~/code-quality~
  - ~/release-process~
  - ~/git-workflow~
  - ~/pr-workflow~
  - ~/repo-settings~
  
 - /docs/project-overview
 - /docs/architecture
 - ~/docs/er-diagram~
 - /docs/secrets (how to manage)
 - /docs/monitoring
 -

**Comment by hillairet** [comment]
In the interest of making a PR now and keeping it small and easy to review, I won't introduce new content such Code Quality or PR workflow. Each of these items deserve to be their own PR so they are properly reviewed.

I just added the architecture and project overview pages. The ER diagram feels a little premature as well. This is something that should ideally be generated from the code to always be up to date so best to add it when we have a solution to generate it automatically.
